name: Docker Image CI

on:
  push:
    tags:
      - "*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow --tags


      - name: Set Version
        run: |
          echo "GIT_VERSION=$(git describe --match "*.*.*" --always)" >> $GITHUB_ENV
          echo ${{ env.GIT_VERSION }}
