name: Docker Image CI

on:
  push:
    tags:
      - "*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --unshallow --tags -f


      - name: Set Version
        run: |
          echo "GIT_VERSION=$(git describe --match "*.*.*" --always)" >> $GITHUB_ENV

      - name: Print
        run: echo  ${{ env.GIT_VERSION }}
        env:
          GIT_VERSION: ${{ env.GIT_VERSION }}
