name: Docker Image CI

on:
  push:
    tags:
      - "*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Unshallow
        run: git fetch --prune --unshallow


      - name: Set Version
        run: |
          echo "GIT_VERSION=$(git describe --match "*.*.*" --always)" >> $GITHUB_ENV
          echo ${{ env.GIT_VERSION }}
